#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
import re
import sqlite3
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

import psycopg
from psycopg import sql

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SQLITE = Path(os.getenv("CUSTOM_GITHUB_DATA_DIR", ROOT / "data")) / "custom-github.db"
IDENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def qident(name: str) -> str:
    if not IDENT_RE.fullmatch(name):
        raise ValueError(f"Unsafe identifier: {name}")
    return '"' + name.replace('"', '""') + '"'


def tables(conn: sqlite3.Connection) -> list[str]:
    rows = conn.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name").fetchall()
    return [str(row[0]) for row in rows]


def column_type(declared: str, *, integer_pk: bool = False) -> str:
    if integer_pk:
        return "BIGINT"
    value = (declared or "TEXT").upper()
    if "INT" in value:
        return "BIGINT"
    if any(x in value for x in ("REAL", "FLOA", "DOUB")):
        return "DOUBLE PRECISION"
    if "BLOB" in value:
        return "BYTEA"
    if "BOOL" in value:
        return "BOOLEAN"
    return "TEXT"


def safe_default(value: Any) -> str | None:
    if value is None:
        return None
    raw = str(value).strip()
    if re.fullmatch(r"-?[0-9]+(?:\.[0-9]+)?", raw):
        return raw
    if raw.upper() in {"NULL", "CURRENT_TIMESTAMP", "CURRENT_DATE", "CURRENT_TIME", "TRUE", "FALSE"}:
        return raw.upper()
    if len(raw) <= 500 and ((raw.startswith("'") and raw.endswith("'")) or (raw.startswith('"') and raw.endswith('"'))):
        inner = raw[1:-1].replace("'", "''")
        return "'" + inner + "'"
    return None


def build_table_ddl(source: sqlite3.Connection, schema: str, table: str) -> str:
    info = source.execute(f"PRAGMA table_info({qident(table)})").fetchall()
    pk_cols = sorted(((int(row[5]), str(row[1])) for row in info if int(row[5]) > 0), key=lambda x: x[0])
    single_integer_pk = None
    if len(pk_cols) == 1:
        row = next(r for r in info if str(r[1]) == pk_cols[0][1])
        if "INT" in str(row[2]).upper():
            single_integer_pk = str(row[1])
    parts: list[str] = []
    for row in info:
        name = str(row[1])
        typ = column_type(str(row[2]), integer_pk=(name == single_integer_pk))
        segment = f"{qident(name)} {typ}"
        if name == single_integer_pk:
            segment += " GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        elif int(row[3]):
            segment += " NOT NULL"
        default = safe_default(row[4])
        if default is not None:
            segment += f" DEFAULT {default}"
        parts.append(segment)
    if pk_cols and single_integer_pk is None:
        parts.append("PRIMARY KEY (" + ",".join(qident(name) for _, name in pk_cols) + ")")
    return f"CREATE TABLE {qident(schema)}.{qident(table)} (" + ",".join(parts) + ")"


def unique_indexes(source: sqlite3.Connection, table: str) -> list[tuple[str, bool, list[str]]]:
    result: list[tuple[str, bool, list[str]]] = []
    for row in source.execute(f"PRAGMA index_list({qident(table)})").fetchall():
        name = str(row[1])
        unique = bool(row[2])
        origin = str(row[3]) if len(row) > 3 else "c"
        if origin == "pk":
            continue
        cols = [str(x[2]) for x in source.execute(f"PRAGMA index_info({qident(name)})").fetchall()]
        if cols:
            result.append((name, unique, cols))
    return result


def foreign_keys(source: sqlite3.Connection, table: str) -> list[dict[str, Any]]:
    groups: dict[int, list[sqlite3.Row]] = defaultdict(list)
    for row in source.execute(f"PRAGMA foreign_key_list({qident(table)})").fetchall():
        groups[int(row[0])].append(row)
    result = []
    for fk_id, rows in groups.items():
        rows = sorted(rows, key=lambda r: int(r[1]))
        result.append({
            "id": fk_id,
            "table": str(rows[0][2]),
            "from": [str(r[3]) for r in rows],
            "to": [str(r[4]) for r in rows],
            "on_update": str(rows[0][5]),
            "on_delete": str(rows[0][6]),
        })
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description="Verified Custom GitHub SQLite -> PostgreSQL migration")
    parser.add_argument("--sqlite", default=str(DEFAULT_SQLITE))
    parser.add_argument("--dsn", default=os.getenv("CUSTOM_GITHUB_POSTGRES_DSN", ""))
    parser.add_argument("--schema", default="custom_github")
    parser.add_argument("--apply", action="store_true", help="Actually write PostgreSQL")
    parser.add_argument("--replace-schema", action="store_true", help="Drop the target schema before migration")
    args = parser.parse_args()
    if not IDENT_RE.fullmatch(args.schema):
        parser.error("--schema must be a simple PostgreSQL identifier")
    source_path = Path(args.sqlite).expanduser().resolve()
    if not source_path.exists():
        parser.error(f"SQLite database not found: {source_path}")
    source = sqlite3.connect(f"file:{source_path}?mode=ro", uri=True)
    source.row_factory = sqlite3.Row
    source.execute("PRAGMA foreign_keys=ON")
    names = tables(source)
    print(f"Source: {source_path}")
    print(f"Tables: {len(names)}")
    total_rows = 0
    for name in names:
        count = int(source.execute(f"SELECT COUNT(*) FROM {qident(name)}").fetchone()[0])
        total_rows += count
        print(f"  {name}: {count}")
    print(f"Total rows: {total_rows}")
    if not args.apply:
        print("DRY RUN ONLY. Re-run with --apply and CUSTOM_GITHUB_POSTGRES_DSN to migrate.")
        return 0
    if not args.dsn:
        parser.error("--dsn or CUSTOM_GITHUB_POSTGRES_DSN is required with --apply")

    with psycopg.connect(args.dsn, autocommit=False) as target:
        with target.cursor() as cur:
            if args.replace_schema:
                cur.execute(sql.SQL("DROP SCHEMA IF EXISTS {} CASCADE").format(sql.Identifier(args.schema)))
            cur.execute(sql.SQL("CREATE SCHEMA IF NOT EXISTS {}").format(sql.Identifier(args.schema)))
            cur.execute(
                "SELECT tablename FROM pg_catalog.pg_tables WHERE schemaname=%s LIMIT 1",
                (args.schema,),
            )
            existing = cur.fetchone()
            if existing and not args.replace_schema:
                raise RuntimeError(f"Target schema {args.schema!r} is not empty; use --replace-schema only after confirming it is safe")

            for name in names:
                cur.execute(build_table_ddl(source, args.schema, name))

            for name in names:
                rows = source.execute(f"SELECT * FROM {qident(name)}").fetchall()
                columns = [str(d[0]) for d in source.execute(f"SELECT * FROM {qident(name)} LIMIT 0").description]
                if rows:
                    statement = sql.SQL("INSERT INTO {}.{} ({}) VALUES ({})").format(
                        sql.Identifier(args.schema), sql.Identifier(name),
                        sql.SQL(",").join(sql.Identifier(c) for c in columns),
                        sql.SQL(",").join(sql.Placeholder() for _ in columns),
                    )
                    cur.executemany(statement, [tuple(row[c] for c in columns) for row in rows])

            # Recreate SQLite indexes, including UNIQUE constraints represented as auto-indexes.
            used_names: set[str] = set()
            for table in names:
                for original, unique, cols in unique_indexes(source, table):
                    base = re.sub(r"[^A-Za-z0-9_]", "_", original)
                    idx_name = base if IDENT_RE.fullmatch(base) and not base.startswith("sqlite_autoindex") else f"idx_{table}_{'_'.join(cols)}"
                    suffix = 2
                    candidate = idx_name[:55]
                    while candidate in used_names:
                        candidate = f"{idx_name[:50]}_{suffix}"; suffix += 1
                    used_names.add(candidate)
                    cur.execute(
                        sql.SQL("CREATE {} INDEX {} ON {}.{} ({})").format(
                            sql.SQL("UNIQUE") if unique else sql.SQL(""),
                            sql.Identifier(candidate), sql.Identifier(args.schema), sql.Identifier(table),
                            sql.SQL(",").join(sql.Identifier(c) for c in cols),
                        )
                    )

            # Add foreign keys only after all rows exist so copy order cannot break migration.
            for table in names:
                for fk in foreign_keys(source, table):
                    cname = f"fk_{table}_{fk['id']}"[:60]
                    statement = sql.SQL("ALTER TABLE {}.{} ADD CONSTRAINT {} FOREIGN KEY ({}) REFERENCES {}.{} ({})").format(
                        sql.Identifier(args.schema), sql.Identifier(table), sql.Identifier(cname),
                        sql.SQL(",").join(sql.Identifier(c) for c in fk["from"]),
                        sql.Identifier(args.schema), sql.Identifier(fk["table"]),
                        sql.SQL(",").join(sql.Identifier(c) for c in fk["to"]),
                    )
                    on_delete = fk["on_delete"].upper()
                    on_update = fk["on_update"].upper()
                    if on_delete in {"CASCADE", "SET NULL", "RESTRICT", "NO ACTION"}:
                        statement += sql.SQL(" ON DELETE " + on_delete)
                    if on_update in {"CASCADE", "SET NULL", "RESTRICT", "NO ACTION"}:
                        statement += sql.SQL(" ON UPDATE " + on_update)
                    cur.execute(statement)

            # Move identity sequences beyond copied explicit IDs.
            for table in names:
                info = source.execute(f"PRAGMA table_info({qident(table)})").fetchall()
                integer_pks = [str(r[1]) for r in info if int(r[5]) == 1 and "INT" in str(r[2]).upper()]
                if len(integer_pks) == 1:
                    col = integer_pks[0]
                    cur.execute("SELECT pg_get_serial_sequence(%s,%s)", (f'{args.schema}.{table}', col))
                    seq = cur.fetchone()[0]
                    if seq:
                        cur.execute(
                            sql.SQL("SELECT COALESCE(MAX({}),0) FROM {}.{}").format(sql.Identifier(col), sql.Identifier(args.schema), sql.Identifier(table))
                        )
                        maximum = int(cur.fetchone()[0])
                        cur.execute("SELECT setval(%s,%s,%s)", (seq, max(maximum, 1), maximum > 0))

            # Verification is mandatory before commit.
            mismatches: list[str] = []
            for name in names:
                src_count = int(source.execute(f"SELECT COUNT(*) FROM {qident(name)}").fetchone()[0])
                cur.execute(sql.SQL("SELECT COUNT(*) FROM {}.{}").format(sql.Identifier(args.schema), sql.Identifier(name)))
                dst_count = int(cur.fetchone()[0])
                if src_count != dst_count:
                    mismatches.append(f"{name}: sqlite={src_count} postgres={dst_count}")
            if mismatches:
                raise RuntimeError("Row-count verification failed: " + "; ".join(mismatches))

            cur.execute(sql.SQL("CREATE TABLE {}._migration_meta (migrated_at TIMESTAMPTZ NOT NULL DEFAULT now(), source_path TEXT NOT NULL, table_count INTEGER NOT NULL, row_count BIGINT NOT NULL)").format(sql.Identifier(args.schema)))
            cur.execute(sql.SQL("INSERT INTO {}._migration_meta(source_path,table_count,row_count) VALUES(%s,%s,%s)").format(sql.Identifier(args.schema)), (str(source_path), len(names), total_rows))
        target.commit()
    print(f"MIGRATION VERIFIED: {len(names)} tables / {total_rows} rows copied to schema {args.schema}")
    print("SQLite was not modified. Do not switch runtime backend until the PostgreSQL compatibility gate is enabled.")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        raise SystemExit(1)
